# This task contains steps for Failover: Promoting a slave to master
# To be run on the slave node. 
- name: Set geo-replication indexing on
  shell: "gluster volume set {{ gluster_features_georep_slavevol }} geo-replication.indexing on"
  delegate_to: "{{ gluster_features_georep_slavenodes[0] }}"
  run_once: true

- name: Set changelog as on
  shell: "gluster volume set {{ gluster_features_georep_slavevol }} changelog on"
  delegate_to: "{{ gluster_features_georep_slavenodes[0] }}"
  run_once: true
