---
- hosts: servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the geo-rep session
    geo_rep:
       action: create
       mastervol: "{{ gluster_features_georep_mastervol }}"
       slavevol: >
         "{{ gluster_features_georep_slavenodes[0] }}:{{ gluster_features_georep_slavevol }}"
       force: true
       georepuser: "{{ georepuser }}"
    run_once: true
    when: gluster_features_georep_slavenodes is defined
