---
# tasks file for gluster_hci
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prerequisites.yml
  tags:
    - prerequisites

# Configure glusterd to use ipv6.
# Don't try to configure if FQDN is not set.
- name: Configure glusterd to use ipv6
  import_tasks: glusterd_ipv6.yml
  when: gluster_features_enable_ipv6 | default(false)
  tags:
    - setupipv6

# Create GlusterFS volumes on the nodes
- name: Create GlusterFS volumes
  collections:
    - gluster.gluster
  import_tasks: hci_volumes.yml
  tags:
    - hcivolcreate

# We disable hosted engine pre-check for now.
# Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1674600#c9

# Run pre-requisite check for deploying Hosted Engine
# - name: Check disk latency
#   import_tasks: hosted_engine_pre_check.yml
#   tags:
#     - latencycheck

# Setup ssl on nodes if specified
- name: Enable SSL on hosts
  collections:
    - gluster.gluster
  import_tasks: ssl-setup.yml
  when: gluster_features_enable_ssl|default(false)
  tags:
    - sslsetup
